name: Draft

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    name: Release Drafter
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  update_prerelease_title:
    name: Update Prerelease Title
    runs-on: ubuntu-latest
    steps:
      - name: Update releae title
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const releases = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const prerelease = releases.data.find(r => r.prerelease);
            console.log(prerelease)
            await github.prelease.updateRelease({
              name: 'HI'
            })