name: Draft

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    name: Release Drafter
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}