name: Pre-release

on:
  release:
    types: [prereleased]

jobs:
  release:
    name: Deploy to Production 
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: ${{ steps.get_prerelease.outputs.release_url }}
    steps:
      - name: Get Pre-release
        id: get_prerelease
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const release = await github.repos.getRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ github.event.release.id }}
            });
            core.setOutput('release_url', release.html_url);
            core.setOutput('release_id', release.id);
      - name: Deploy
        id: Deploy
        run: echo Deployed to ${{ steps.get_prerelease.outputs.release_url }} with ID ${{ steps.get_prerelease.outputs.release_id }}