name: Pre-release

on:
  release:
    types: [prereleased]

jobs:
  release:
    name: Deploy to Production 
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: ${{ steps.get_prerelease.outputs.release_url }}
    steps:
      - name: Get Pre-release
        id: get_prerelease
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const releases = await github.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const prerelease = releases.data.find(r => r.prerelease);
            core.setOutput('release_url', prerelease.url);
            core.setOutput('release_id', prerelease.id);
      - name: Deploy
        id: Deploy
        run: echo Deployed to ${{ steps.get_prerelease.outputs.release_url }} with ID ${{ steps.getprerelease.outputs.release_id }}